source/javascripts/all.js
source/layouts/layout.erb

Let's open source this repo and tell the world!

[ready] Add link to source in source

---

source/stylesheets/_header.scss

[ready] Fix logo aspect ratio for IE

---

source/localizable/_google_analytics.erb
source/localizable/bedankt.html.erb

Conversions didn't get tracked yet, hope this helps.

[ready] Prevent double rendering of GA script on thanks

---

source/javascripts/_ebook-form.js
source/javascripts/_popup.js
source/javascripts/all.js.erb
source/stylesheets/base/_forms.scss

[ready] E-book form conversion & validation

---

source/stylesheets/_layout.scss
source/stylesheets/main.css.scss

sticky footer

---

locales/nl.yml
source/localizable/_product_highlights.erb

Hans asked me (partly on behalf of Joris) to make these content changes. Personally I don't like it, but I can understand why. For me this feels like a quick fix for mediocre content.

[READY?] Textual changes

---

source/blog/2015-10-07-conversie-van-historische-LMS-data-naar-capp-probleemloos.html.markdown
source/blog/2015-10-07-conversie-van-tcg-en-edumanager-naar-capp-succesvol.html.markdown

2015-10-07-conversie-van-tcg-en-edumanager-naar-capp-succesvol.html.markdown

Update pieters blog

---

source/seminar.html.erb
source/stylesheets/_seminar.scss
source/stylesheets/main.scss

[WIP] Hugo/seminar convenant

---

source/blog/2015-12-14-innovatie-die-wat-oplevert.html.markdown

Please review this one more time..

Blog Joep about innovation

---

source/robots.txt
source/sitemap.xml.builder

[READY] Remove danke and 404 from indexation

---

source/blog/2016-01-04-aantoonbaar-bekwaam-in-het-kader-van-convenant-medische-technologie.html.markdown

Author was Marian and not Joep

[READY] Change author of CMT blog

---

data/testimonials.yml
data/testimonials_de.yml

[READY] Remove testimonial Martina de Vos

---

source/localizable/404.html.erb

This is needed to track the 404's.

[READY] Better title for 404

---

source/workshop-convenant-mt.html.erb

Update itemprop URL to direct to the right page

[READY] Minor update Workshop page

---

source/workshop-convenant-mt.html.erb

[Ready] Remove introduce text

---

source/blog/2015-05-20-animated-loading-indicator-with-isometric-cubes.html.markdown
source/layouts/layout.erb

[READY] Set NL locale on blog loading indicator

---

data/downloads.yml

[READY] New produktblatt CAPP

---

source/layouts/layout.erb
source/localizable/_google_analytics.erb
source/localizable/bedankt.html.erb
source/robots.txt

Please review @sn3p @fatboypunk

[READY] Google Analytics and more

---

source/localizable/_footer.erb
source/stylesheets/_footer.scss
source/stylesheets/_header.scss

See https://github.com/DefactoSoftware/website/issues/140

[READY] Layout and styling improvements

---

source/blog/2016-01-22-drie-redenen-om-meer-intercollegiaal-te-toetsen.html.markdown
source/blog/2016-02-01-snelkookpanimplementatie-gemeente-den-haag-twee-weken-uit-en-thuis.html.markdown

[READY] blog Joost OCW

---

source/localizable/index.html.erb

[READY] remove learntec announcement from the DE homepage

---

source/localizable/index.html.erb

[READY] remove workshop announcement

---

source/blog/2016-01-08-the-future-is-now.html.markdown

[READY] remove line

---

source/localizable/over-ons/_over-ons.de.md.erb
source/localizable/over-ons/_over-ons.nl.md.erb

Add some links to our vacancies on the jobs site to the about pages

[READY] add links to vacancies to about pages

---

source/localizable/_google_analytics.erb

[READY] proper way of domain linking with GA

---

source/localizable/convenant-medische-technologie.nl.erb

Should be /kwaliteitspaspoort instead of kwaliteitspaspoort.

[READY] fix broken link on cmt page

---

locales/de.yml
locales/nl.yml
source/localizable/learningspaces.html.erb

[READY] link to german registration from LS page

---

source/localizable/over-ons/_over-ons.nl.md.erb

Minor change in text on the about us page

[READY] change de to duitsland on links to german jobs

---

locales/de.yml
locales/nl.yml
source/localizable/over-ons/_sidebar.erb

Adds a links to the jobs site to the sidebar on the about us page. 
This one I previously had in a wrong PR/branch.

[READY] add links to jobs to about sidebar

---

source/localizable/_german_news.erb

[READY] Event update

---

locales/nl.yml
source/localizable/learningspaces.html.erb
source/localizable/learningspaces/_learningspaces.nl.md.erb

[READY] new copy defacto LS page NL

---

source/localizable/koppelingen/_koppelingen.nl.md.erb

removes the leerstation zorg copy from the koppelingen page

[READY] remove leerstation zorg copy

---

locales/de.yml
locales/nl.yml
source/localizable/_footer.erb
source/localizable/_json_ld.erb

[READY] Enhance site attributes

---

source/localizable/media/_media.de.md.erb

[READY] Fix typo Presse page

---

source/localizable/over-ons/_over-ons.nl.md.erb

- set correct links to vacancies
- add accountmanager new business

[READY] Correct links to Jobs

---

source/layouts/layout.erb

Sharing looks better with Defacto in og:title.

[READY] add defacto to open graph titles

---

source/localizable/hosting/_hosting.nl.md.erb

New text by Hans about Hosting & Security.

[WIP] New copy hosting security

---

source/localizable/_json_ld.erb

[READY] add youtube account to structured data

---

source/localizable/kwaliteitspaspoort/_kwaliteitspaspoort.nl.md.erb

I made a few improvements to the list text.

[READY] KPP List

---

source/localizable/e-learning-starterkit.html.erb
source/localizable/e-learning.html.erb

[READY] add organization field to elearning forms

---

locales/nl.yml
source/localizable/_popup-ebook.erb
source/stylesheets/components/_popup.scss

Found the required doesn't do much #243

[READY] Update pop up

---

source/localizable/elearning/_elearning.de.md.erb

Added it to our own YT channel instead of Jesse's.

[READY] video High Risk Medication Defacto 

---

source/localizable/_solutions-overview.erb

Mistakenly didn't change a link in a home partial

[READY] set link to capp-lms

---

source/layouts/layout.erb
source/localizable/_json_ld.erb

[READY] add google plus profile

---

config.rb
locales/de.yml
locales/nl.yml
source/blog/index.html.erb
source/stylesheets/_blog.scss
source/stylesheets/main.scss

[READY] Paginate the blog

---

source/blog/de/2016-07-15-e-learning-freiheit.html.markdown

[wip] add a german blog by martina

---

source/blog/nl/2016-07-18-alweer-een-systeem.html.markdown

- title: ? comes always before !
- correct link to bigger graphic

[READY] Blog: correct the link and update the title

---

source/stylesheets/_blog.scss

We had a little issues with the blog index css, it targeted too much on a lot of (sub) pages. 
So I made this little dirty css with @sn3p and made an issue to fix it better in the future. We got 89 blogs the time to fix it. :-)

[READY] Dirty fix for blog index css

---

config.rb
source/layouts/layout.erb
source/stylesheets/_blog.scss

Fixes https://github.com/DefactoSoftware/website/issues/265
@RonaldDijkstra I've got it working (see `page_classes` helper):
```rb
classes.sub!(/blog_\d+_index/, "blog_index")
```
Also changed some other blog checks/conditionals that weren't valid anymore using pagination.
For easier checking I've added `is_blog?` and `is_blog_index?` helpers (`is_blog_article?` is already provided by Middleman).
**please review and test**

[READY] Blog pagination fixes

---

source/blog/nl/2016-07-18-alweer-een-systeem.html.markdown

[READY] Blog about system mailto links

---

source/localizable/360-feedback.html.erb
source/localizable/capp-lms.html.erb
source/localizable/e-learning.html.erb
source/localizable/hosting-security.html.erb
source/localizable/implementaties.html.erb
source/localizable/koppelingen.html.erb
source/localizable/kwaliteitspaspoort.html.erb
source/localizable/learningspaces.html.erb

I forgot that there are a lot of pages with the client partial. I changed the location, should've update them all. 
Note to self: first test a build, then deploy. 
Note to self 2: test everywhere

[READY] fix all client partials

---

source/blog/nl/2016-07-12-bedrijfsuitje-defacto-2016.html.markdown

[READY] remove extra asterisk

---

source/stylesheets/_blog.scss

[READY] change sizes of h2 and h3 on the blog

---

locales/de.yml
locales/nl.yml
source/localizable/_footer.erb
source/localizable/contact/_contact.de.md.erb

info@defactolearning.de for german website.

[READY] localize email

---

locales/de.yml
locales/nl.yml
source/localizable/_contact-info.erb
source/localizable/_footer.erb

- localize email on `contact_info` too
- remove redundant phone numbers from locales
- use `unless` instead of `if`
Fixes #273

[READY] Localize last email

---

source/localizable/_footer.erb

[READY] Blog link available in german footer

---

source/javascripts/_popup.js

It counts way too much eventjes.

[READY] fix popup show count

---

locales/de.yml
source/blog/_featured.erb
source/stylesheets/_blog.scss

By request of the German team I added a title to the featured blog partial on the homepage. 
(Changed the title and the padding a little bit to make it better fit.)

[READY] add a title to homepage featured blog partial

---

source/localizable/referenties.html.erb

> Joost·10:49
> Ronald, in de referentie van Equens staat nog een HTML dingetje achter het logo

[READY] fix li equens logo

---

data/testimonials_de.yml
source/localizable/index.html.erb
source/stylesheets/_testimonials.scss

A single featured testimonial on the homepage.

[READY] single featured testimonial on the homepage

---

source/localizable/_german_news.erb
source/localizable/media/_media.de.md.erb
source/stylesheets/_german_news.scss

[WIP] update german news partial

---

source/localizable/_german_news.erb
source/stylesheets/_german_news.scss

Add some more context and update the spacing a little.

[READY] Another calendar update

---

source/localizable/contact/_contact.de.md.erb
source/localizable/contact/_contact.nl.md.erb

[READY] Remove fax number

---

locales/de.yml
source/localizable/elearning/_elearning.de.md.erb

[READY] update content of german e-learning page

---

source/localizable/koppelingen/_koppelingen.de.md.erb

[READY] update content of german koppelingen page

---

locales/de.yml
source/localizable/implementaties/_implementaties.de.md.erb

[READY] update content german implement page

---

locales/de.yml
source/localizable/contact.html.erb
source/localizable/contact/_contact.de.md.erb

[READY] update content german kontakt page

---

source/stylesheets/components/_popup.scss

Fit the pop-up to smaller desktop and laptop screens!  
Fixes #313

[READY] Make the pop-up fit better

---

source/localizable/kwaliteitspaspoort.html.erb
source/localizable/kwaliteitspaspoort/_kwaliteitspaspoort.de.md.erb
source/stylesheets/_kpp.scss

[READY] Update KPP Page 2

---

source/localizable/elearning/_elearning-starterkit.nl.md.erb
source/stylesheets/_layout.scss
source/stylesheets/base/_variables.scss
source/stylesheets/main.scss

[READY] Update inner UL 

---

source/javascripts/_menu.js
source/localizable/_header.erb
source/stylesheets/_header.scss
source/stylesheets/_home.scss

[READY] Style header classes instead of id's

---

data/testimonials_de.yml
data/testimonials_nl.yml
source/localizable/index.html.erb

[READY] add testimonial to german homepage

---

source/localizable/learningspaces.html.erb
source/stylesheets/_learningspaces.scss

By request. 
Replaces the browser with the video.

[READY] add LS animation to LS page

---

source/javascripts/_forms.js.erb
source/javascripts/_select.js
source/javascripts/all.js
source/localizable/demo-aanvragen.html.erb

[READY] fix mobile menu

---

source/javascripts/_popup.js

Fixes #368
@RonaldDijkstra this should fix it.

[READY] Only init popup when present in DOM

---

locales/de.yml
source/localizable/360-feedback/_360feedback.de.md.erb

Just a few small changes by request.

[READY] German typos

---

source/layouts/layout.erb
source/localizable/demo-aanvragen.html.erb
source/localizable/productsheet-downloaden.html.erb

Add data to frontmatter to make the ebook popup optional on pages where applicable.

[READY] make the popup optional

---

data/team.yml
source/localizable/over-ons/_team.erb

[READY] add niels and sort alphabetically on lastname

---

source/localizable/_german_news.erb
source/stylesheets/_german_news.scss
source/stylesheets/base/_variables.scss

[READY] fix style and update content german event calendar

---

source/stylesheets/_home.scss
source/stylesheets/components/_hero.scss

[READY] Fit hero better on mobile

---

locales/de.yml
source/localizable/capp-bilden.de.erb
source/localizable/capp/_capp-bilden.de.md.erb
source/stylesheets/_capp.scss
source/stylesheets/_layout.scss

This adds 'focus keyword' E-Learning Software a bit more to the page and changes the layout just a little bit to fit the content better.

[READY] update content of capp bilden page

---

locales/de.yml
source/localizable/capp/_capp-entwickeln.de.erb

[READY] update content capp entwickeln page

---

source/javascripts/_forms.js.erb
source/javascripts/_popup.js
source/localizable/_popup-ebook.erb
source/stylesheets/components/_popup.scss

[READY] update ebook popup

---

locales/de.yml
source/localizable/capp-bilden.de.erb
source/localizable/capp-entwickeln.de.erb
source/stylesheets/_capp.scss

[WIP] add titles to german capp pages

---

locales/de.yml
locales/nl.yml
source/localizable/learningspaces.html.erb

[READY] add german video to LS page

---

config.rb
locales/de.yml

[READY] rename kundenreferenz to kundenstimmen

---

source/layouts/layout.erb
source/stylesheets/_blog.scss
source/stylesheets/base/_variables.scss

[READY] Update blog linter issues

---

source/blog/_blog-article-preview.erb
source/blog/_featured.erb
source/blog/index.html.erb
source/stylesheets/_blog.scss
source/stylesheets/components/_base.scss
source/stylesheets/components/_blog-article-preview.scss

Thanks @sn3p for working this out with me! 👍

[READY] add featured image to featured post on homepage 

---

locales/nl.yml

[READY] change dutch testimonials title

---

locales/nl.yml

[READY] add dutch animation to LS page

---

source/blog/_blog-article-author.erb
source/blog/_blog-article-preview.erb
source/layouts/blog_post_layout.erb
source/stylesheets/_blog.scss
source/stylesheets/components/_blog-article-preview.scss

I changed related to 5 posts, because 10 feels to much to me in this layout.

[READY] Add featured images to related posts below a blog post

---

locales/nl.yml
source/localizable/kwaliteitspaspoort.html.erb

[READY] Update header dutch kpp page

---

data/testimonials_nl.yml

A temporary change of the homepage testimonial, this one is more relevant for zorg/ziekenhuizen/kpp. Still old though, but new content is coming

[READY] change homepage testimonial temporary

---

locales/de.yml
locales/nl.yml
source/blog/_blog-article-author.erb
source/layouts/blog_post_layout.erb

Add a dot to german date notations in blogs through yaml.

[READY] make date notation in yaml

---

source/blog/de/2017-01-10-lernen-ist-arbeit-ist-lernen.html.markdown

According to @AnneNH there should be a CAPITAL in the first heading.

[READY] add capital to first heading

---

data/team.yml
source/localizable/convenant-medische-technologie.nl.erb

[READY] Update team januari

---

source/localizable/events-overview/_events-overview.nl.md.erb

[READY] Remove SAMevent from homepage

---

data/team.yml
source/blog/nl/2016-07-12-bedrijfsuitje-defacto-2016.html.markdown
source/blog/nl/2016-11-28-learningspaces-op-websummit.html.markdown
source/blog/nl/2016-12-22-waardevolle-kennis-delen-met-learningspaces.html.markdown

[READY] Update team again

---

source/localizable/elearning/_elearning.de.md.erb

[READY] Add video back to e-learning page

---

Gemfile
Gemfile.lock
config.rb
source/layouts/layout.erb

Also specified a separate source section for `https://rails-assets.org` gems.

Install jQuery gem

---

source/localizable/e-learning-starterkit.html.erb

Ignore NL for e-learning starterkit

---

config.rb
locales/de.yml
source/localizable/hosting/_hosting.de.md.erb

new content for implementation and security de

---

source/localizable/capp/_capp-lms.en.md.erb

Fix typo CAPP LMS page EN

---

source/jobs/de/business-developer.html.markdown
source/jobs/de/consultant.html.markdown
source/jobs/de/software-developer.html.markdown

Linking the German vacancies to Homerun too

Link German vacancies to Homerun

---

source/blog/de/2017-12-01-compliance-und-sicherheit-im-krankenhaus-safety-first.html.markdown

Apply right link for social image of compliance blog

---

locales/en.yml

Add alt text to english popup close button

---

source/localizable/capp/_capp-lms.nl.md.erb

Edit 3 typo's on page CAPP LMS

Edit typo CAPP LMS

---

source/localizable/privacy-policy/_privacy-policy.nl.md.erb

Updating the privacy policy to version 1.2.

Update Privacy Policy

---

source/blog/de/2018-06-14-medizinischer-fachangestellter-im-krankenhaus-entlastung-fur-den-arzt.html.markdown

Add links to MFA blog

---

source/localizable/elearning/_elearning.nl.md.erb

Removal of SCORM information on E-learning webpage

Remove SCORM information from e-learning page

---

source/cases/de/fek-neumunster.html.markdown

Removal of 'CAPP entwickeln' checkmarked product from the FEK Neumünster case

Update products and services section of FEK Neumunster case

---

locales/en.yml

Add key user to contact chat text

---

data/news_de.yml

Change title Projectleiter job

---

source/cases/nl/antoni-van-leeuwenhoek.html.markdown

Fix of the 'Klant sinds' year from 2018 to 2017.

Fix year of Klant sinds for AVL case

---

source/blog/de/2018-09-27-fordermittel-fur-digitale-medien-in-der-beruflichen-bildung-im-gesundheitswesen.html.markdown

Update link to BMBF site

---

source/localizable/evenementenagenda/_events.de.md.erb
source/stylesheets/_evenementenagenda.scss

Let's add another German event. Because I didn't get input, I just copied the copy from the flyer. 
@SusanDefacto @isabelamy can one of you please review the copy?

Add Clubabend 18 okt 

---

source/cases/_case-sidebar.html.erb
source/layouts/post_layout.erb
source/localizable/footer/_footer.erb
source/localizable/zoeken.html.erb
source/stylesheets/layout/_footer.scss

Add ARIA landmarks

---

source/stylesheets/posts/_post-header.scss

On mobile the background is way too big

Use background:cover only on screen size medium and up

---

source/stylesheets/layout/_header.scss

Link-container needs a width or else IE11 doesn't get it :)

Fix dropdown issue in IE11

---

locales/nl.yml
source/localizable/key-user-event.html.erb
source/localizable/key-user-event/_content.nl.md
source/partials/_form.erb

Add RSVP page for key user event

---

source/stylesheets/layout/_header.scss

This makes the main navigation a bit more flexible with flex box.

Fit the main navigation with more items by using flexbox
