DefactoSoftware/website

config.rb
source/javascripts/_ebook-form.js
source/layouts/layout.erb
source/localizable/error.html.erb

[READY] 404 error page

---

source/localizable/_product_highlights.erb
source/localizable/learningspaces.html.erb

On homepage /de and /de/learningspaces correct links. Issue #117 
@dkhgh @sn3p

Correct links to German learningspaces website

---

locales/de.yml
locales/nl.yml
source/convenant-medische-technologie.erb
source/localizable/_popup-ebook.erb
source/localizable/capp.html.erb
source/localizable/contact.html.erb
source/localizable/elearning-starterkit.html.erb
source/localizable/elearning.html.erb
source/localizable/kwaliteitspaspoort.html.erb

To make the most of conversions. 
Please review @sn3p @dkhgh (and deploy if good

[READY] Different Formkeeps

---

source/stylesheets/_convenant.scss

The margin on the `ul` is no longer needed and influenced the ul's in the footer

[READY] Remove margin on <ul> of CMT page

---

source/robots.txt.erb

Blocking the redirected pages was a mistake, we do want robots to find the redirected url's, even if the redirects occur on the client side.

[READY] don't block redirected pages from robots

---

config.rb
source/layouts/layout.erb

Even last weekend we saw German users land on the NL TLD, so we need to make clear for search engines which version of the Defacto site is which. With a bit of help from @sn3p we made a helper to set hreflangs in each version of the site. 
Some more info on this: 
https://support.google.com/webmasters/answer/189077?hl=nl 
https://moz.com/learn/seo/hreflang-tag

[READY] use hreflangs for locales

---

source/stylesheets/base/_tables.scss
source/stylesheets/base/_typography.scss

This fixes the problems I've mentioned in #222, #223 & #224. 
AFAIK we don't need font-feature-settings.

[READY] remove font feature settings

---

source/layouts/layout.erb

Search console alerted me on some hreflang tag (return) errors because the other way round the blog posts don't exist.

[READY] hreflangs unless blog article

---

locales/de.yml
locales/nl.yml
source/blog/_featured.erb

I forgot to translate the read more link in the featured blog section of the homepage.

[READY] localize read more

---

config.rb
source/layouts/layout.erb

Checks if the page exists in another language. If not the flag should point to the homepage of the other language. 
On Defactolearning.de it seems to only link to the homepage for now. 
See the switch here to see how it works when there's no page on the other website: http://www.defacto.nl/convenant-medische-technologie/

[READY] Flag and hreflang links to other language

---

config.rb

This line was accidentally removed: 
`
url = full_url locale_url_for(url, locale: lang)
`
Which destroyed correct use of the hreflangs tag. This PR fixes this.

[READY] fix the hreflangs

---

Rakefile

Fixing https://github.com/DefactoSoftware/website/issues/277
The `rake deploy` task now exits when the the build fails.
This differs from the LearningSpaces landing page we're using a [`deploy` bash script](https://github.com/DefactoSoftware/LearningSpaces-Landing/blob/master/deploy).

[READY] Prevent deployment when build fails

---

.hound.yml
.scss-lint.yml

I'd like to make some changes to Hound settings, like the depths of nesting and selector depths. I made 2 commits, one with the default settings and one with changes. 
I have a few questions about the settings LS uses, becasue they differ from the default: 
LS: 
```
ExtendDirective:
enabled: true
QualifyingElement:
enabled: true
allow_element_with_attribute: true
allow_element_with_class: true
allow_element_with_id: false
SelectorFormat:
enabled: true
convention: hyphenated_BEM
SpaceAfterVariableColon:
enabled: false
style: one_space 
```
Default:
```
ExtendDirective:
enabled: false
QualifyingElement:
enabled: true
allow_element_with_attribute: false
allow_element_with_class: false
allow_element_with_id: false
SelectorFormat:
enabled: true
convention: hyphenated_lowercase …
```

[READY] Hound settings

---

config.rb
source/localizable/convenant-medische-technologie.nl.erb
source/localizable/hosting-security.nl.erb
source/localizable/hosting.de.erb

Checks if there's a unique_for_locale var in frontmatter. If that's true, it sends the flag link to the homepage of the other TLD. 
What do you think, is this sustainable enough @fatboypunk? 
Issue #239

[READY] add unique for locale in frontmatter

---

source/stylesheets/_header.scss

When `$desktop-mode: $large-up;` (860px) hide the toggle instead of `medium-up `(640px).

[READY] update mobile toggle view

---

source/layouts/layout.erb

`href_langs` tells (search engine) robots which version of a page is correct for a certain language. 
If unique_for_locale is true, do not return href_langs, or else it points to a non existing (404) page! 
```
<link rel="alternate" href="http://www.defacto.nl/learningspaces/" hreflang="nl-nl" />
<link rel="alternate" href="http://www.defactolearning.de/learningspaces/" hreflang="de-de" />
```

[READY] add locale check to hreflangs in main layout

---

source/localizable/capp-lms.nl.erb

defacto.nl/capp-lms doesn't exist on defactolearning.de,  
there it's /capp-bilden and /capp-entwickeln.  
-> Point it to the homepage

[READY] add unique for locale to capp lms page

---

source/blog/_featured.erb
source/blog/feed.xml.builder
source/blog/index.html.erb
source/layouts/blog_post_layout.erb

This was added recently to team.yml to make a better alphabetic order on the team page, but was not added at blog posts and the feed.xml
Here's when I made the add the last featured  to Iwanna **de** Jonge

[READY] add prefix to blog author

---

source/layouts/blog_post_layout.erb
source/stylesheets/_blog.scss

[READY] remove blog author no image

---

config.rb

Hm, featured_image gets a hash on build. Let's ignore the folder with these images on build?

[READY] ignore featured image folder for asset hash

---

source/layouts/layout.erb
source/stylesheets/main.scss

We used this before to hide the Google conversion frame in legacy IE browser. 
```
// Hide Google Conversion iframe
iframe[name="google_conversion_frame"] {
display: none !important;
float: left;
font-size: 0 !important;
height: 0 !important;
line-height: 0 !important;
margin-top: -13px;
width: 0 !important;
}
```
But it can be done with a setting. 
`var google_conversion_format = 3;`
http://stackoverflow.com/questions/13162495/whats-difference-values1-2-3-of-google-conversion-format 
With no var google conversion format = 3 and no CSS, there's a 13 px white stroke below the page:
With conversion format = 3 the 13 px are gone: 
part of #347 cleansing

[READY] Change google conversion frame setting

---

source/localizable/360-feedback.html.erb
source/localizable/capp-bilden.de.erb
source/localizable/capp-entwickeln.de.erb
source/localizable/capp-lms.nl.erb
source/localizable/contact.html.erb
source/localizable/convenant-medische-technologie.nl.erb
source/localizable/e-learning-starterkit.html.erb
source/localizable/e-learning.html.erb
source/localizable/kwaliteitspaspoort.html.erb
source/localizable/learningspaces.html.erb

Don't show the e-book pop-up on pages with other main conversion goals. 
In my opinion main conversion goals are: 
**- CAPP LMS (pages):** download productsheet
**- Kwaliteitspaspoort:** fill in the form in the bottom
**- LearningSpaces:** click through to register or to LS-landing
**- 360-feedback:** click through to register
**- Contact:** fill in the form
**- Convenant MT:** fill in the form in the bottom
**- E-Learning Starterkit:** fill in the form or download e-book in the bottom 
**- E-Learning:** fill in the form in the bottom
Fixes #388

[READY] remove popup from pages with other main goals

---

source/blog/feed.xml.builder

Makes sure the `/blog/feed.xml`'s contain the right TLD.

Localize blog feed

---

Gemfile
Gemfile.lock
config.rb
source/stylesheets/_bedankt.scss
source/stylesheets/_blog.scss
source/stylesheets/_capp.scss
source/stylesheets/_clients.scss
source/stylesheets/_convenant.scss
source/stylesheets/_conversion.scss
source/stylesheets/_error.scss
source/stylesheets/_feature_list.scss

Installed Autoprefixer with the following browser support:
```rb
config.browsers = ["last 3 versions", "Explorer >= 9"]
```
This means all `@include` vendor prefix mixins can be removed, and replaces with standard css properties. I've already started doing this but the rest can be done later.

Autoprefixer

---

config.rb
source/localizable/datenschutz.html.erb

Specify more to ignore languages instead of just 1.
Can be used later on for the ignore build methode.

Use ignore_lang for flag and alternate links
